// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmBup2D1zm4LxgzriNU732tjNeW2sPw44',
    appId: '1:747636372400:web:3431e555aa2814c6d11c75',
    messagingSenderId: '747636372400',
    projectId: 'ilabs-db6a4',
    authDomain: 'ilabs-db6a4.firebaseapp.com',
    storageBucket: 'ilabs-db6a4.firebasestorage.app',
    measurementId: 'G-D9R7SE4MR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCddYZC3_wFER2laErsMBSclLEDGnXrm54',
    appId: '1:747636372400:android:9ae9ee6875df5149d11c75',
    messagingSenderId: '747636372400',
    projectId: 'ilabs-db6a4',
    storageBucket: 'ilabs-db6a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwwA-yr6Cmhad8uociAmHhQfblCFkGag',
    appId: '1:747636372400:ios:2976a15f06fcb383d11c75',
    messagingSenderId: '747636372400',
    projectId: 'ilabs-db6a4',
    storageBucket: 'ilabs-db6a4.firebasestorage.app',
    iosBundleId: 'com.example.ilabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwwA-yr6Cmhad8uociAmHhQfblCFkGag',
    appId: '1:747636372400:ios:2976a15f06fcb383d11c75',
    messagingSenderId: '747636372400',
    projectId: 'ilabs-db6a4',
    storageBucket: 'ilabs-db6a4.firebasestorage.app',
    iosBundleId: 'com.example.ilabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmBup2D1zm4LxgzriNU732tjNeW2sPw44',
    appId: '1:747636372400:web:deccb178dbea0133d11c75',
    messagingSenderId: '747636372400',
    projectId: 'ilabs-db6a4',
    authDomain: 'ilabs-db6a4.firebaseapp.com',
    storageBucket: 'ilabs-db6a4.firebasestorage.app',
    measurementId: 'G-KYK8H1VPLJ',
  );
}
